export type Product = {
  slug: string; name: string; short: string; description: string; features: string[]; gradient: string; icon: string;
};

export const products: Product[] = [
  {slug:"corrugated-boxes",name:"Corrugated Boxes",short:"Strong & durable boxes for safe packaging.",description:"Reliable corrugated packaging designed for protection, handling and storage across a wide range of industries.",features:["High strength and durability","Lightweight and cost-effective","Available in various sizes","Eco-friendly and recyclable","Custom printing available"],gradient:"linear-gradient(135deg,#c98a42,#8d5528)",icon:"▣"},
  {slug:"packaging-tapes",name:"Packaging Tapes",short:"High quality tapes for secure sealing.",description:"Dependable packaging tapes for clean, secure and efficient carton sealing.",features:["Strong adhesion","Smooth application","Reliable carton sealing","Multiple widths available","Suitable for industrial use"],gradient:"linear-gradient(135deg,#f4d58d,#c49a48)",icon:"◉"},
  {slug:"bubble-wrap",name:"Bubble Wrap",short:"Protective packaging for fragile items.",description:"Cushioning bubble wrap that helps protect fragile products from scratches, impact and handling damage.",features:["Lightweight cushioning","Impact protection","Easy to cut and wrap","Flexible for different products","Suitable for fragile goods"],gradient:"linear-gradient(135deg,#f4f4f4,#b9c1c7)",icon:"○"},
  {slug:"stretch-film",name:"Stretch Film",short:"Durable stretch film for added protection.",description:"Stretch film for securing cartons, pallets and products during storage and transportation.",features:["Excellent stretchability","Secure load holding","Tear-resistant options","Multiple sizes available","Ideal for transport protection"],gradient:"linear-gradient(135deg,#e8edf0,#aeb7bd)",icon:"◍"},
  {slug:"packaging-pouches",name:"Packaging Pouches",short:"Pouches for safe and hygienic storage.",description:"Practical packaging pouches for organized, clean and protected product storage.",features:["Clean and hygienic","Lightweight","Multiple sizes","Easy handling","Custom options available"],gradient:"linear-gradient(135deg,#f9f8f1,#c7c0a8)",icon:"◇"},
  {slug:"corrugated-sheets",name:"Corrugated Sheets",short:"High quality sheets for industrial uses.",description:"Versatile corrugated sheets for separators, wrapping, layering and protective industrial packaging.",features:["Good rigidity","Lightweight construction","Easy to cut and shape","Recyclable","Suitable for industrial applications"],gradient:"linear-gradient(135deg,#b9864b,#72502f)",icon:"▤"}
];
